-- Crear base de datos si no existe
CREATE DATABASE IF NOT EXISTS superhero;
USE superhero;

-- Crear tabla superpower (necesaria para los poderes)
CREATE TABLE IF NOT EXISTS superpower (
  id INT NOT NULL AUTO_INCREMENT,
  power_name varchar(200) DEFAULT NULL,
  CONSTRAINT pk_superpower PRIMARY KEY (id)
);

-- Insertar algunos poderes de ejemplo
INSERT IGNORE INTO superpower (id, power_name) VALUES
(1, 'Agility'),
(2, 'Accelerated Healing'),
(3, 'Lantern Power Ring'),
(4, 'Dimensional Awareness'),
(5, 'Cold Resistance'),
(6, 'Durability'),
(7, 'Stealth'),
(8, 'Energy Absorption'),
(9, 'Flight'),
(10, 'Danger Sense'),
(11, 'Underwater breathing'),
(12, 'Marksmanship'),
(13, 'Weapons Master'),
(14, 'Power Augmentation'),
(15, 'Animal Attributes'),
(16, 'Longevity'),
(17, 'Intelligence'),
(18, 'Super Strength'),
(19, 'Cryokinesis'),
(20, 'Telepathy'),
(21, 'Energy Armor'),
(22, 'Energy Blasts'),
(23, 'Duplication'),
(24, 'Size Changing'),
(25, 'Density Control'),
(26, 'Stamina'),
(27, 'Astral Travel'),
(28, 'Audio Control'),
(29, 'Dexterity'),
(30, 'Omnitrix'),
(31, 'Super Speed'),
(32, 'Possession'),
(33, 'Animal Oriented Powers'),
(34, 'Weapon-based Powers'),
(35, 'Electrokinesis'),
(36, 'Darkforce Manipulation'),
(37, 'Death Touch'),
(38, 'Teleportation'),
(39, 'Enhanced Senses'),
(40, 'Telekinesis'),
(41, 'Energy Constructs'),
(42, 'Force Fields'),
(43, 'Self-Sustenance'),
(44, 'Anti-Gravity'),
(45, 'Empathy'),
(46, 'Power Nullifier'),
(47, 'Radiation Control'),
(48, 'Psionic Powers'),
(49, 'Elasticity'),
(50, 'Substance Secretion'),
(51, 'Elemental Transmogrification'),
(52, 'Technopath/Cyberpath'),
(53, 'Photographic Reflexes'),
(54, 'Seismic Power'),
(55, 'Animation'),
(56, 'Precognition'),
(57, 'Mind Control'),
(58, 'Fire Control'),
(59, 'Power Suit'),
(60, 'Super Breath'),
(61, 'Invulnerability'),
(62, 'Energy Resistance'),
(63, 'Telepathy Resistance'),
(64, 'Molecular Manipulation'),
(65, 'Heat Generation'),
(66, 'Adaptation'),
(67, 'Gliding'),
(68, 'Power Absorption'),
(69, 'Web Creation'),
(70, 'Reality Warping'),
(71, 'Odin Force'),
(72, 'Symbiote Costume'),
(73, 'Speed Force'),
(74, 'Phoenix Force'),
(75, 'Molecular Dissipation'),
(76, 'Vision - Telescopic'),
(77, 'Magnetism'),
(78, 'Mind Blast'),
(79, 'Night Vision'),
(80, 'Shapeshifting'),
(81, 'Enhanced Hearing'),
(82, 'Nova Force'),
(83, 'Insanity'),
(84, 'Hypnokinesis'),
(85, 'Animal Control'),
(86, 'Natural Armor'),
(87, 'Intangibility'),
(88, 'Enhanced Sight'),
(89, 'Molecular Combustion'),
(90, 'Omnipresence'),
(91, 'Light Control'),
(92, 'Peek-a-Boo'),
(93, 'Cloaking'),
(94, 'Changing Armor'),
(95, 'Power Cosmic'),
(96, 'Biokinesis'),
(97, 'Water Control'),
(98, 'Radiation Immunity'),
(99, 'Vision - Thermal'),
(100, 'Vision - Night'),
(101, 'Vision - X-Ray'),
(102, 'Astral Projection'),
(103, 'Electrical Transport'),
(104, 'Fire Resistance'),
(105, 'Projection'),
(106, 'Summoning'),
(107, 'Enhanced Memory'),
(108, 'Reflexes'),
(109, 'Invulnerability'),
(110, 'Energy Constructs'),
(111, 'Force Fields'),
(112, 'Self-Sustenance'),
(113, 'Anti-Gravity'),
(114, 'Empathy'),
(115, 'Power Nullifier'),
(116, 'Radiation Control'),
(117, 'Psionic Powers'),
(118, 'Elasticity'),
(119, 'Substance Secretion'),
(120, 'Elemental Transmogrification');

-- Verificar que las tablas principales existan
SELECT 'Verificando tablas...' as status;
SHOW TABLES LIKE 'superhero';
SHOW TABLES LIKE 'hero_attribute';  
SHOW TABLES LIKE 'hero_power';
SHOW TABLES LIKE 'superpower';
SHOW TABLES LIKE 'attribute';

-- Mostrar algunos datos de ejemplo
SELECT 'Datos de ejemplo:' as info;
SELECT COUNT(*) as total_heroes FROM superhero LIMIT 1;
SELECT COUNT(*) as total_powers FROM superpower LIMIT 1;
